name: CI/CD - Testes Automatizados

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test-api:
    name: Testes API com Playwright
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./api-playwright
        run: npm install

      - name: Run API tests
        working-directory: ./api-playwright
        run: npx playwright test

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: api-playwright-report
          path: ./api-playwright/test-results

  test-frontend:
    name: Testes Frontend E2E com Playwright + Cucumber
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./front-playwright-cucumber
        run: npm install

      - name: Run Frontend tests
        working-directory: ./front-playwright-cucumber
        run: npx cucumber-js --import support/custom-world.js --import support/hooks.js --import steps/*.js features

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: front-playwright-cucumber-report
          path: ./front-playwright-cucumber/reports

  test-mobile:
    name: Testes Mobile com Appium + Robot Framework
    runs-on: ubuntu-latest

    services:
      appium:
        image: appium/appium
        ports:
          - 4723:4723

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        working-directory: ./appium-tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install robotframework-appiumlibrary

      - name: Run Mobile tests
        working-directory: ./appium-tests
        run: robot tests/

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: appium-tests-report
          path: ./appium-tests/report.html
